# This is a basic workflow to help you get started with Actions

name: Newman Run

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: npm install newman-reporter-htmlextra

    - name: Run API Tests
      run: newman run https://www.getpostman.com/collections/c0d9a1bfd6aa5717ffd1 --reporters cli,htmlextra