# This is a basic workflow to help you get started with Actions

name: Newman Run

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
      
    - name: Make directory for results
      run: mkdir -p testResults

    - name: Run API Tests
      run: newman run gorest.co.in.postman_collection.json --environment gorest.co.in.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/index.html

    - name: Output test results
      uses: actions/upload-artifact@v3
      with:
        name: RunReports
        path: testResults
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: testResults